# Server configuration
server:
  port: 8090

logging:
  file: logs/process.${HOSTNAME:localhost}.${server.port}
  level:
    com:
      example:
        hellographql: debug

jwt:
  enabled: true
  secret: graphql
  expires: 86400000
  prefix: "Bearer "
  header: Authorization

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/petclinic?useSSL=true
    username: root
    password: test
  jpa:
    hibernate:
      use-new-id-generator-mappings: true